/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

import model.bean.Cliente;
import model.bean.Funcionario;
import model.dao.ClienteDAO;
import model.dao.FuncionarioDAO;

import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;

import control.ControleFuncionario;
import control.TabelaFuncionario;

import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author vagui
 */
public class Cadastro_Funcionario extends javax.swing.JFrame {
	
	private TableModelFuncionario tableModelFuncionario;

    /**
     * Creates new form Cadastro_Funcionario
     */
    public Cadastro_Funcionario() {
        initComponents();
        this.tableModelFuncionario = new TableModelFuncionario();
        this.jTBfuncionario.setModel(tableModelFuncionario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCPF = new javax.swing.JLabel();
        jTextCPF = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlFuncao = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextTelefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBfuncionario = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        JComboBox comboFuncao = new JComboBox();
        comboFuncao.setModel(new DefaultComboBoxModel(new String[] {"Pizzaiolo", "Entregador", "Atendente", "Gerente"}));
        jButton1 = new javax.swing.JButton();
        jButton1.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\checkicon.png"));
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		String funcao = String.valueOf(comboFuncao.getSelectedItem());
        		ControleFuncionario cadastrar = new ControleFuncionario();
        		cadastrar.cadastarFuncionario(Long.parseLong(jTextCPF.getText()), jTextNome.getText(), Integer.parseInt(jTextTelefone.getText()),funcao);        		
        	}
        });
       
        jButton3 = new javax.swing.JButton();
        jButton3.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\deleteicon.png"));
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Funcionário");

        jlCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCPF.setText("CPF:");

        jlNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlNome.setText("Nome:");

        jlTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTelefone.setText("Telefone:");

        jlFuncao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlFuncao.setText("Fun\u00E7\u00E3o:");

        jTBfuncionario.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"CPF","Nome", "Telefone", "Fun\u00E7\u00E3o"
        	}
        ));
        jScrollPane1.setViewportView(jTBfuncionario);
        
        jButtonEditar = new javax.swing.JButton();
        jButtonEditar.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\editicon.png"));
        jButtonEditar.addActionListener(new ActionListener() {
       

			public void actionPerformed(ActionEvent arg0) {
				Funcionario f = tableModelFuncionario.pegarFuncionario(jTBfuncionario.getSelectedRow());
				TabelaFuncionario tf = new TabelaFuncionario();
				tf.editarFuncionario(f);
        	}
        });

        jLabel7.setFont(new Font("Georgia", Font.BOLD, 25)); // NOI18N
        jLabel7.setText("Cadastro de Funcion\u00E1rios");

        jButton1.setText("Adicionar");

        jButtonEditar.setText("Editar");

        jButton3.setText("Cancelar");
        
        comboFuncao.setToolTipText("");
        
        JLabel lblBusca = new JLabel("Busca");
        
        jTextBuscaFuncionario = new JTextField();
        jTextBuscaFuncionario.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyReleased(KeyEvent arg0) {
        		FuncionarioDAO busca = new FuncionarioDAO();
        		try {
					tableModelFuncionario.pegarListaFuncionarios(busca.readForDesc(jTextBuscaFuncionario.getText()));
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
        	}
        });
        jTextBuscaFuncionario.setColumns(10);
        
        btnExcluir = new JButton("Excluir");
        btnExcluir.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\trashicon.png"));
        btnExcluir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Funcionario f = tableModelFuncionario.pegarFuncionario(jTBfuncionario.getSelectedRow());
        		TabelaFuncionario tf = new TabelaFuncionario();
        		tf.excluirFuncionario(f);
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        					.addGap(34)
        					.addComponent(jButtonEditar, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
        					.addGap(35)
        					.addComponent(btnExcluir, GroupLayout.PREFERRED_SIZE, 93, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
        					.addComponent(jButton3)
        					.addGap(14))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 484, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jlFuncao)
        								.addComponent(jlNome)
        								.addComponent(jlCPF))
        							.addGap(53)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jTextBuscaFuncionario, GroupLayout.PREFERRED_SIZE, 285, GroupLayout.PREFERRED_SIZE)
        								.addComponent(comboFuncao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jTextCPF, GroupLayout.PREFERRED_SIZE, 353, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jTextNome, GroupLayout.PREFERRED_SIZE, 353, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jTextTelefone, GroupLayout.PREFERRED_SIZE, 355, GroupLayout.PREFERRED_SIZE)))
        						.addComponent(jlTelefone)
        						.addComponent(lblBusca))
        					.addContainerGap(40, Short.MAX_VALUE))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 361, GroupLayout.PREFERRED_SIZE)
        					.addGap(45))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(10)
        			.addComponent(jLabel7)
        			.addGap(12)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jlCPF)
        				.addComponent(jTextCPF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jlNome)
        				.addComponent(jTextNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jlTelefone)
        				.addComponent(jTextTelefone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jlFuncao)
        				.addComponent(comboFuncao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(10)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblBusca)
        				.addComponent(jTextBuscaFuncionario, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(16)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jButtonEditar, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(16)
        					.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(16)
        					.addComponent(btnExcluir, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlFuncao;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBfuncionario;
    private javax.swing.JTextField jTextCPF;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextTelefone;
    private JTextField jTextBuscaFuncionario;
    private JButton btnExcluir;
}
