/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import model.bean.Cliente;
import model.bean.Funcionario;
import model.dao.ClienteDAO;
import model.dao.FuncionarioDAO;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;

import control.ControleCliente;
import control.TabelaCliente;
import control.TabelaFuncionario;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author vagui
 */
public class Cadastro_Clientes extends javax.swing.JFrame {
	
	private TableModelCliente tableModelCliente;
    /**
     * Creates new form CadastroClientes
     */
    public Cadastro_Clientes() {
        initComponents();
        this.tableModelCliente = new TableModelCliente();
        this.jTBCliente.setModel(tableModelCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jCPF = new javax.swing.JLabel();
        jlRua = new javax.swing.JLabel();
        jlBairro = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jTextCPF = new javax.swing.JTextField();
        jTextRua = new javax.swing.JTextField();
        jTextBairro = new javax.swing.JTextField();
        jTextTelefone = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jlBusca = new javax.swing.JLabel();
        jTextBuscaCliente = new javax.swing.JTextField();
        jTextBuscaCliente.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyReleased(KeyEvent args) {
        		ClienteDAO busca = new ClienteDAO();
        		try {
					tableModelCliente.pegarListaClientes(busca.readForDesc(jTextBuscaCliente.getText()));
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
				
        	}
        });
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBCliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton1.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\checkicon.png"));
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		ControleCliente cadastrar = new ControleCliente();
        		cadastrar.cadastrarCliente(jTextCPF.getText(), jTextNome.getText(), Integer.parseInt(jTextTelefone.getText()), jTextRua.getText(), jTextBairro.getText(),jTextCidade.getText(), jTextEstado.getText(), jTextEmail.getText());        		
        	}
        });
        jButton2 = new javax.swing.JButton();
        jButton2.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\editicon.png"));
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Cliente c = tableModelCliente.pegarCliente(jTBCliente.getSelectedRow());
				TabelaCliente tc = new TabelaCliente();
				tc.editarCliente(c);
        	}
        });
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.exit(0);
        	}
        });
        jButton3.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\deleteicon.png"));
        jLabel8 = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jTextCidade = new javax.swing.JTextField();
        jlEstado = new javax.swing.JLabel();
        jTextEstado = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Clientes");

        jCPF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCPF.setText("CPF:");

        jlRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlRua.setText("Rua:");

        jlBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlBairro.setText("Bairro:");

        jlTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlTelefone.setText("Telefone:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlBusca.setText("Buscar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBusca)
                    .addComponent(jTextBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTBCliente.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"C\u00F3digo", "Nome", "Rua", "Bairro", "Telefone"
        	}
        ));
        jScrollPane1.setViewportView(jTBCliente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 221, GroupLayout.PREFERRED_SIZE)
        			.addGap(217))
        );
        jPanel2.setLayout(jPanel2Layout);

        jButton1.setText("Adicionar");

        jButton2.setText("Editar");

        jButton3.setText("Cancelar");

        jLabel8.setFont(new Font("Georgia", Font.BOLD, 25)); // NOI18N
        jLabel8.setText("Cadastro de Clientes");

        jlCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlCidade.setText("Cidade:");

        jlEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEstado.setText("Estado:");

        jlEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlEmail.setText("E-mail:");

        jlNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlNome.setText("Nome:");
        
        JButton btnExcluir = new JButton("Excluir");
        btnExcluir.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\trashicon.png"));
        btnExcluir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		Cliente c = tableModelCliente.pegarCliente(jTBCliente.getSelectedRow());
        		TabelaCliente tc = new TabelaCliente();
        		tc.excluirCliente(c);        		
        	}
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jlTelefone)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jTextTelefone, GroupLayout.PREFERRED_SIZE, 363, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addComponent(jlRua)
        					.addGroup(layout.createSequentialGroup()
        						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        							.addComponent(jlEstado)
        							.addComponent(jlCidade))
        						.addPreferredGap(ComponentPlacement.UNRELATED)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jTextEstado, GroupLayout.PREFERRED_SIZE, 364, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jTextCidade, GroupLayout.PREFERRED_SIZE, 364, GroupLayout.PREFERRED_SIZE)))
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(jlEmail)
        						.addGap(18)
        						.addComponent(jTextEmail, GroupLayout.PREFERRED_SIZE, 364, GroupLayout.PREFERRED_SIZE))
        					.addGroup(layout.createSequentialGroup()
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jlBairro)
        							.addComponent(jCPF))
        						.addGap(18)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jTextCPF, GroupLayout.PREFERRED_SIZE, 364, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jTextRua, GroupLayout.PREFERRED_SIZE, 364, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jTextBairro, GroupLayout.PREFERRED_SIZE, 364, GroupLayout.PREFERRED_SIZE)))
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(jlNome)
        						.addGap(18)
        						.addComponent(jTextNome, GroupLayout.PREFERRED_SIZE, 364, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(79, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(121, Short.MAX_VALUE)
        			.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
        			.addGap(100))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(25, Short.MAX_VALUE)
        			.addComponent(jButton1)
        			.addGap(28)
        			.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
        			.addGap(32)
        			.addComponent(btnExcluir, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
        			.addGap(19))
        		.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(36)
        			.addComponent(jLabel8)
        			.addPreferredGap(ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jlNome)
        				.addComponent(jTextNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jCPF, Alignment.TRAILING)
        				.addComponent(jTextCPF, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jlRua)
        				.addComponent(jTextRua, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jlBairro)
        				.addComponent(jTextBairro, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextCidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jlCidade))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextEstado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jlEstado))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jlEmail))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextTelefone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jlTelefone))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 246, GroupLayout.PREFERRED_SIZE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(20)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(1)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)))
        						.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(21)
        					.addComponent(btnExcluir, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jCPF;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlBusca;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBCliente;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextCPF;
    private javax.swing.JTextField jTextRua;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextTelefone;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextBuscaCliente;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextEstado;
}

