package view;

import javax.swing.table.DefaultTableModel;

import control.ControleProduto;
import control.TabelaProduto;
import model.bean.Produto;
import model.dao.ProdutoDAO;

import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import java.awt.Font;

public class Cadastro_Cardapio extends javax.swing.JFrame {
	TableModelProduto tableModelProduto;
    /**
     * Creates new form Cadastrar_Cardapio
     */
    public Cadastro_Cardapio() {
        initComponents();
        this.tableModelProduto = new TableModelProduto();
        this.table_cardapio.setModel(tableModelProduto);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        txtCardapioDescricao = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtCardapioValor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_cardapio = new javax.swing.JTable();
        bAdicionarCardapio = new javax.swing.JButton();
        bAdicionarCardapio.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\checkicon.png"));
        bEditarCardapio = new javax.swing.JButton();
        bEditarCardapio.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\editicon.png"));
        bEditarCardapio.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Produto p = tableModelProduto.pegarProduto(table_cardapio.getSelectedRow());
				TabelaProduto tp = new TabelaProduto();
				tp.editarProduto(p);
        	}
        });
        bCancaelarCardapio = new javax.swing.JButton();
        bCancaelarCardapio.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		System.exit(0);
        	}
        });
        bCancaelarCardapio.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\deleteicon.png"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Cardapio");

        jLabel2.setFont(new Font("Cambria", Font.PLAIN, 14)); // NOI18N
        jLabel2.setText("Descri\u00E7\u00E3o:");

        lblValor.setFont(new Font("Cambria", Font.PLAIN, 14)); // NOI18N
        lblValor.setText("Valor:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        table_cardapio.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"Nome", "Descri\u00E7\u00E3o", "Valor"
        	}
        ));
        jScrollPane1.setViewportView(table_cardapio);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        bAdicionarCardapio.setText("Adicionar");
        bAdicionarCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ControleProduto cadastrar = new ControleProduto();
        		cadastrar.cadastrarProduto(textCardapioTipo.getText(), txtCardapioDescricao.getText(), Double.parseDouble(txtCardapioValor.getText()), Integer.parseInt(textCardapioQuantidade.getText()));
            }
        });

        bEditarCardapio.setText("Editar");

        bCancaelarCardapio.setText("Cancelar");
        
        JLabel lblQuantidade = new JLabel("Quantidade:");
        lblQuantidade.setFont(new Font("Cambria", Font.PLAIN, 14));
        
        textCardapioQuantidade = new JTextField();
        textCardapioQuantidade.setColumns(10);
        
        lblTipo = new JLabel("Tipo:");
        lblTipo.setFont(new Font("Cambria", Font.PLAIN, 14));
        
        textCardapioTipo = new JTextField();
        textCardapioTipo.setColumns(10);
        
        btnExcluir = new JButton("Excluir");
        btnExcluir.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\trashicon.png"));
        btnExcluir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Produto p = tableModelProduto.pegarProduto(table_cardapio.getSelectedRow());
        		TabelaProduto tp = new TabelaProduto();
        		tp.excluirProduto(p); 
        	}
        });
        
        lblBusca = new JLabel("Busca:");
        lblBusca.setFont(new Font("Cambria", Font.PLAIN, 14));
        
        textCardapioBusca = new JTextField();
        textCardapioBusca.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyReleased(KeyEvent arg0) {
        		ProdutoDAO busca = new ProdutoDAO();
        		try {
					tableModelProduto.pegarListaProdutos(busca.readForDesc(textCardapioBusca.getText()));
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        	}
        });
        textCardapioBusca.setColumns(10);
        
        JLabel lblNewLabel = new JLabel("");
        lblNewLabel.setIcon(new ImageIcon("C:\\Users\\vagui\\Desktop\\PizzariaPagnossim\\icon\\cardapioicon.png"));
        
        JLabel lblDkwqopdwkqpo = new JLabel("Registre um novo card\u00E1pio");
        lblDkwqopdwkqpo.setFont(new Font("Georgia", Font.BOLD, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(75, Short.MAX_VALUE)
        			.addComponent(lblDkwqopdwkqpo, GroupLayout.PREFERRED_SIZE, 357, GroupLayout.PREFERRED_SIZE)
        			.addGap(33)
        			.addComponent(lblNewLabel)
        			.addGap(24))
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2)
        						.addComponent(lblTipo))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(txtCardapioValor, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        							.addGap(29)
        							.addComponent(lblQuantidade)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(textCardapioQuantidade))
        						.addComponent(textCardapioTipo)
        						.addComponent(textCardapioBusca, GroupLayout.PREFERRED_SIZE, 425, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtCardapioDescricao, GroupLayout.PREFERRED_SIZE, 425, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblValor))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblBusca))
        				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 514, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(22, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(25)
        			.addComponent(bAdicionarCardapio, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
        			.addGap(25)
        			.addComponent(bEditarCardapio, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        			.addGap(39)
        			.addComponent(btnExcluir, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
        			.addGap(38)
        			.addComponent(bCancaelarCardapio, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(23)
        					.addComponent(lblDkwqopdwkqpo))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(15)
        					.addComponent(lblNewLabel)))
        			.addGap(28)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2)
        				.addComponent(txtCardapioDescricao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(textCardapioTipo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblTipo))
        			.addGap(29)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblValor)
        				.addComponent(txtCardapioValor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblQuantidade)
        				.addComponent(textCardapioQuantidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(15)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblBusca)
        				.addComponent(textCardapioBusca, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(bCancaelarCardapio, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnExcluir, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(1)
        					.addComponent(bEditarCardapio, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(1)
        					.addComponent(bAdicionarCardapio, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(16, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Cardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdicionarCardapio;
    private javax.swing.JButton bCancaelarCardapio;
    private javax.swing.JButton bEditarCardapio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_cardapio;
    private javax.swing.JTextField txtCardapioDescricao;
    private javax.swing.JTextField txtCardapioValor;
    private JTextField textCardapioQuantidade;
    private JLabel lblTipo;
    private JTextField textCardapioTipo;
    private JButton btnExcluir;
    private JLabel lblBusca;
    private JTextField textCardapioBusca;
}
